import {renderScore,renderCatalog,renderFijas,cepreEmblem} from './upgrades.js';
import {orbitHTML,mountOrbits} from './orbit.js';
import {renderProfile,syncProfileBadge} from './profile.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const store={get(k,d){try{return JSON.parse(localStorage.getItem('universe-preview-'+k))??d}catch{return d}},set(k,v){try{localStorage.setItem('universe-preview-'+k,JSON.stringify(v));return true}catch{return false}}};
const safe=s=>{try{const u=new URL(s,'https://universetostudy.com');return u.protocol==='https:'?esc(u.href):'#'}catch{return '#'}};
function openVideoPreview(id,title,channel){const dialog=$('#video-preview');if(!dialog)return;
 $('#video-frame').innerHTML=`<iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?autoplay=1&amp;rel=0" title="${esc(title)}" allow="accelerometer;autoplay;clipboard-write;encrypted-media;gyroscope;picture-in-picture" allowfullscreen loading="lazy"></iframe>`;
 $('#video-preview-meta').textContent=`${title} · ${channel}`;
 $('#video-preview-link').href=`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`;
 document.body.classList.add('modal-open');dialog.showModal();
 if(!dialog.dataset.wired){dialog.dataset.wired='1';dialog.addEventListener('close',()=>{$('#video-frame').innerHTML=''})}
}
const routes={
 '/explorar':['Tu universo de estudio','PLATAFORMA / 01','Un lugar para conectar lo que aprendes, lo que practicas y lo que quieres alcanzar.'],
 '/biblioteca':['Conocimiento en órbita.','BIBLIOTECA / 02','Encuentra tu siguiente lectura. Colecciones, materiales y libros organizados para acompañarte antes y después del ingreso.'],
 '/biblioteca/universe':['Hecho en Universe.','UNIVERSE × CICLESOLUS','Solucionarios CEPREUNI 2027-1. La colección conserva las portadas, los autores y la disponibilidad del catálogo.'],
 '/biblioteca/cuzcano':['Catálogo Cuzcano.','BIBLIOTECA / EDITORIALES','Material preuniversitario y solucionarios CEPREUNI organizados por curso.'],
 '/biblioteca/lumbreras':['Catálogo Lumbreras.','BIBLIOTECA / EDITORIALES','Explora las colecciones y encuentra el libro que acompaña a tu siguiente tema.'],
 '/biblioteca/librosuniversitarios':['Más allá del ingreso.','BIBLIOTECA / UNIVERSITARIA','Raymond Chang y coautores. Química y fisicoquímica, con sus ediciones e idiomas identificados.'],
 '/cepreuni/ciclopre20271':['Tu material. Tu avance.','CEPREUNI / CICLO PRE 2027-1','Documentos del ciclo, libros y clases. Las mismas fuentes, en un espacio más claro.'],
 '/cepreuni':['Tu próxima etapa.','CEPREUNI / 2027-1','Un centro de estudio para tu ciclo: materiales, temas, evaluaciones y una ruta para llegar preparado.'],
 '/temario':['Entender empieza aquí.','MAPA DEL CONOCIMIENTO','Explora el temario de admisión y CEPREUNI. Abre un tema, revisa sus conceptos y registra lo que ya estudiaste.'],
 '/clases':['Una idea más clara.','CLASES / VIDEOTECA','Videos organizados por curso. Filtra, busca y continúa aprendiendo desde el canal de origen.'],
 '/planificador':['Una intención. Un plan.','TU TRAYECTORIA','Convierte tus próximos temas en pasos concretos. Este tablero guarda tus tareas únicamente en este navegador.'],
 '/fijas-cepreuni':['Prioriza con criterio.','CEPREUNI / PRIMERA PC','Explora el tipo de problema asociado a cada tema del modelo histórico. Una referencia de preparación, nunca una garantía del examen.'],
 '/admision':['Tu futuro toma forma.','ADMISIÓN / UNI','Conoce el proceso, explora tus opciones y conecta tu preparación con información verificable.'],
 '/simulacros':['Practicar con propósito.','LABORATORIO / EVALUACIÓN','Elige tu enfoque, revisa qué estudiar y continúa al simulador conectado cuando quieras evaluar tu preparación.'],
 '/examenes':['Aprende de cada examen.','ARCHIVO / CEPREUNI','Conecta evaluaciones, temas y materiales. El archivo de esta propuesta distingue los recursos disponibles de los servicios conectados.'],
 '/calculadora':['Pon tu meta en perspectiva.','CEPREUNI / PUNTAJES','Tus notas, tu carrera y las referencias históricas. Una calculadora para orientar tu preparación, no para prometer una vacante.'],
 '/unitalk':['El conocimiento se comparte.','COMUNIDAD / UNITALK','Encuentra tu comunidad y sigue conectado con Universe. Las conversaciones reales permanecen en el servicio original.'],
 '/account':['Tu espacio, a tu manera.','CUENTA / PREFERENCIAS','Personaliza esta experiencia y accede a tu cuenta real cuando lo necesites.'],
 '/ranking':['Tu avance tiene contexto.','COMUNIDAD / RANKING','El diseño del seguimiento, sin inventar usuarios ni puntajes. Tus resultados reales se consultan en la plataforma conectada.'],
 '/docentes-cepreuni':['Encuentra tu próximo salón.','CEPREUNI / GUÍA DE AULAS','Accede a docentes, salones y horarios del ciclo. La información vigente se mantiene en la guía original.'],
 '/informacion-cepreuni':['El ciclo, más claro.','CEPREUNI / INFORMACIÓN','Documentos, evaluaciones y recursos reunidos para orientarte durante tu preparación.'],
 '/nosotros':['El origen es la curiosidad.','ACERCA DE UNIVERSE','Una comunidad educativa independiente que reúne recursos para postulantes UNI y estudiantes CEPREUNI.'],
 '/metodologia-editorial':['Claridad desde la fuente.','UNIVERSE / METODOLOGÍA','La confianza empieza por distinguir el material, su procedencia, su disponibilidad y sus límites.'],
 '/correcciones':['Mejoramos contigo.','UNIVERSE / CORRECCIONES','Si encuentras una errata, un enlace roto o información desactualizada, ayúdanos a ubicarla con precisión.'],
 '/contacto':['Hablemos de tu siguiente paso.','UNIVERSE / CONTACTO','Los canales originales de Universe, reunidos en un mismo espacio.'],
 '/terminos':['Las reglas, a la vista.','INFORMACIÓN / TÉRMINOS','Esta propuesta visual no modifica las condiciones de uso de Universe. Consulta siempre la versión publicada.'],
 '/privacidad':['Tu información importa.','INFORMACIÓN / PRIVACIDAD','Conoce qué permanece en tu navegador en esta demostración y cuándo estás saliendo hacia otro servicio.'],
};
let data,videoData,ui,view,home,routeVersion=0,toastTimer;
const link=(url,label,cls='button',live=false)=>`<a class="${cls}" href="${safe(url)}" ${live||!url.startsWith('/')?'data-live target="_blank" rel="noopener noreferrer"':''}>${esc(label)} ${ui.icon('arrow-up-right')}</a>`;
const internal=(url,label,cls='button')=>`<a class="${cls}" href="${esc(url)}">${esc(label)} ${ui.icon('arrow-right')}</a>`;
const note=(text)=>`<div class="p-notice">${text}</div>`;
const sub=(title,right='')=>`<div class="p-subhead"><h2>${title}</h2><span>${right}</span></div>`;
const tile=(url,title,text,icon='orbit',foot='Explorar',live=false)=>`<a class="p-panel p-tile" href="${esc(url)}" ${live?'data-live target="_blank" rel="noopener noreferrer"':''}>${ui.icon(icon)}<h3>${esc(title)}</h3><p>${esc(text)}</p><span class="tile-foot">${esc(foot)}${ui.icon(live?'arrow-up-right':'arrow-right')}</span></a>`;
const logoTile=(url,title,text,logoId,foot='Explorar')=>`<a class="p-panel p-tile logo-tile" href="${esc(url)}"><span class="tile-logo"><img src="${esc(data.logos[logoId])}" alt="Logo de ${esc(title)}" loading="lazy"></span><h3>${esc(title)}</h3><p>${esc(text)}</p><span class="tile-foot">${esc(foot)}${ui.icon('arrow-right')}</span></a>`;
const stats=rows=>`<div class="p-statbar">${rows.map(([a,b])=>`<div><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('')}</div>`;
const orbit=orbitHTML;
const miniBooks=()=>'<div class="mini-books" aria-hidden="true"><img src="/universe-ui/assets/quimica.webp" alt=""><img src="/universe-ui/assets/algebra.webp" alt=""><img src="/universe-ui/assets/geometria.webp" alt=""></div>';
const empty=text=>`<div class="p-empty">${esc(text)}</div>`;
function toast(text){let el=$('.local-toast');if(!el){el=document.createElement('div');el.className='local-toast';el.setAttribute('role','status');document.body.append(el)}el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3500)}
function pathName(){return decodeURI(location.pathname).replace(/\/$/,'').replace(/\.html$/,'')||'/'}
function sidebar(path){const items=[['/explorar','Plataforma','grid'],['/cepreuni','CEPREUNI','cap'],['/biblioteca','Biblioteca','book'],['/temario','Temario','list'],['/clases','Clases','play'],['/planificador','Planificador','calendar'],['/simulacros','Simulacros','target'],['/examenes','Exámenes','layers'],['/admision','Admisión UNI','cap'],['/calculadora','Calculadora','calculator'],['/unitalk','UNITALK','users'],['/ranking','Ranking','orbit'],['/docentes-cepreuni','Guía de aulas','grid']];return `<span>TODO CONECTA</span><nav aria-label="Secciones de Universe">${items.map(([url,t,i])=>`<a href="${url}" ${path===url||(url==='/biblioteca'&&path.startsWith('/biblioteca/'))?'aria-current="page"':''}>${ui.icon(i)}${t}</a>`).join('')}</nav><div class="rail-foot"><b>UNIVERSE / GALAXY</b><br>Una propuesta local.<br>Tu sitio publicado sigue intacto.</div>`}
function head(path){const r=routes[path]||['Aún no estamos aquí.','UNIVERSE / 404','No encontramos esta página. Puedes volver a la plataforma.'];return `<div class="page-topline"><span><a href="/">Universe</a> / <a href="/explorar">Plataforma</a> / ${esc(r[0].replace(/\.$/,''))}</span></div><div class="page-head"><span class="eyebrow">${r[1]}</span><h1 id="page-title" tabindex="-1">${r[0]}</h1><p>${r[2]}</p></div>`}
async function route(focus=false){const token=++routeVersion,p=pathName();const isHome=p==='/';home.hidden=!isHome;$('#platform').hidden=isHome;document.body.classList.toggle('in-platform',!isHome);$('.brand').href='/';$('.footer-brand').href='/';$$('.header .nav a').forEach(a=>a.setAttribute('aria-current',a.getAttribute('href')===p?'page':'false'));if(isHome){document.title='Universe — El origen de tu siguiente idea';return}document.title=`${routes[p]?.[0]||'Página no encontrada'} — Universe`;$('.side-rail').innerHTML=sidebar(p);view.innerHTML=head(p)+'<div class="page-view" id="page-view"></div>';const out=$('#page-view');if(!data){out.innerHTML=empty('Conectando tus recursos…');try{data=await fetch('/universe-ui/data/platform.json').then(r=>{if(!r.ok)throw Error('Datos no disponibles');return r.json()})}catch{out.innerHTML=note('No se pudieron cargar los recursos. Recarga esta página.');return}}if(token!==routeVersion)return;
 const catalogs={'/biblioteca/universe':'universe','/biblioteca/cuzcano':'cuzcano','/biblioteca/lumbreras':'lumbreras','/biblioteca/librosuniversitarios':'college','/cepreuni/ciclopre20271':'materials'};
 if(catalogs[p])catalog(out,catalogs[p]);
 else if(p==='/explorar')overview(out);
 else if(p==='/biblioteca')library(out);
 else if(p==='/cepreuni'||p==='/informacion-cepreuni')cepre(out);
 else if(p==='/temario')syllabus(out);
 else if(p==='/clases')await classes(out,token);
 else if(p==='/planificador')planner(out);
 else if(p==='/fijas-cepreuni')cepre(out);
 else if(p==='/calculadora')calculator(out);
 else if(p==='/admision')admissions(out);
 else if(p==='/examenes'||p==='/simulacros')practice(out,p);
 else if(p==='/account')account(out);
 else if(p==='/unitalk'||p==='/contacto')community(out,p);
 else if(p==='/ranking'||p==='/docentes-cepreuni')connected(out,p);
 else if(routes[p])information(out,p);
 else out.innerHTML=internal('/explorar','Volver a la plataforma');
 mountOrbits();syncProfileBadge();
 if(focus)$('#page-title')?.focus({preventScroll:true});
}
function overview(out){out.innerHTML=`<section class="p-panel p-feature"><div><span class="p-label">UNA RUTA PARA CADA OBJETIVO</span><h2>Tu siguiente idea<br>ya tiene un lugar.</h2><p>No necesitas tener todo resuelto. Empieza por un concepto, una lectura o una pregunta.</p><div class="page-actions">${internal('/temario','Explorar mi temario','button primary')}${internal('/planificador','Crear mi ruta','text-button')}</div></div>${orbit()}</section>${sub('Elige tu próxima conexión','Herramientas de Universe')}<div class="p-grid">${ui.tools.map(t=>tile(t.url,t.name,t.desc,t.icon)).join('')}${tile('/cepreuni?panel=fijas','Fijas CEPREUNI','Primera PC, examen final y prueba de selección.','target')}</div>`}
// /biblioteca es el índice de la biblioteca, no un escaparate: la vista previa de portadas de la
// colección Universe × Ciclesolus vive en su propio catálogo, y aquí solo se enumeran las colecciones
// y las editoriales, cada una con su logo entero.
function library(out){const all=Object.values(data.catalogs).reduce((n,a)=>n+a.length,0);const pubs=data.publishers||[];
 out.innerHTML=`${stats([[all,'recursos catalogados'],[String(pubs.length).padStart(2,'0'),'editoriales'],['2027-1','ciclo preuniversitario']])}${sub('Encuentra tu colección','Cada logo abre su catálogo')}<div class="p-grid two logo-grid">${logoTile('/cepreuni/ciclopre20271','Materiales CEPREUNI','Documentos del ciclo, libros y clases con su vista previa.','cepreuni',data.catalogs.materials.length+' recursos')}${logoTile('/biblioteca/universe','Universe × Ciclesolus','Seis cursos con portadas originales. Álgebra en modo lector.','universe',data.catalogs.universe.length+' libros')}${logoTile('/biblioteca/librosuniversitarios','Libros universitarios','Raymond Chang y coautores. Ediciones e idiomas identificados.','uni',data.catalogs.college.length+' libros')}${logoTile('/biblioteca/lumbreras','Lumbreras','Libros rojos, azules, esenciales y otras colecciones.','lumbreras',data.catalogs.lumbreras.length+' libros')}${logoTile('/biblioteca/cuzcano','Cuzcano','Colecciones de preparación y solucionarios por curso.','cuzcano',data.catalogs.cuzcano.length+' libros')}</div>${sub('Todas las editoriales','Las que no tienen catálogo propio abren su carpeta de origen')}<div class="publisher-grid">${pubs.map(p=>{const ext=p.href.startsWith('http');return `<a class="publisher-card${p.flat?' is-flat':''}" href="${esc(p.href)}"${ext?' data-live target="_blank" rel="noopener noreferrer"':''} aria-label="${esc(p.name)}"><img src="${esc(p.logo)}" alt="${esc(p.name)}" loading="lazy"><span>${esc(p.action||(ext?'Abrir':'Catálogo'))}${ext?' ↗':''}</span></a>`}).join('')}</div>${note('Los archivos se abren en su fuente original. La disponibilidad depende de los permisos de cada archivo.')}`}
function catalog(out,key){renderCatalog(out,key,data)}

function cepre(out){out.innerHTML=`<section class="p-panel p-feature"><div><span class="p-label">CICLO PRE / 2027-1</span><h2>Prepárate para<br>lo que viene.</h2><p>Tu ciclo, conectado: pasa del tema a la clase, de la clase al material y del material a tu plan.</p><div class="page-actions">${internal('/cepreuni/ciclopre20271','Abrir mis materiales','button primary')}${internal('/cepreuni?panel=fijas','Explorar fijas','text-button')}</div></div>${cepreEmblem()}</section>${sub('Tu centro de estudio')}<div class="p-grid four">${tile('/temario','Temario','Los conceptos de cada semana.','list')}${tile('/clases','Clases','Explicaciones a tu ritmo.','play')}${tile('/examenes','Evaluaciones','Prepara tu siguiente práctica.','target')}${tile('/docentes-cepreuni','Aulas','Horarios y docentes.','grid')}</div><section id="cepre-fijas" class="cepre-fijas"></section>${sub('En el horizonte','Septiembre 2026 · Hora de Lima')}<div class="p-split"><div class="p-panel"><div class="p-chips" id="page-cycles"><button data-c="pre" aria-pressed="true">Pre</button><button data-c="basic" aria-pressed="false">Básico</button><button data-c="ien" aria-pressed="false">IEN</button></div><div id="page-schedule"></div></div><div class="p-panel"><span class="p-label">ANTES DE TU EVALUACIÓN</span><h2 style="margin-top:15px">Una ruta más clara.</h2><p>Revisa el alcance de tu práctica, identifica los temas que necesitas reforzar y anótalos en tu tablero.</p><div class="page-actions">${internal('/planificador','Organizar mi preparación','button primary')}</div><p class="source-note">Las fechas proceden del calendario configurado en Universe. Confirma cualquier actualización en CEPREUNI.</p></div></div>`;const render=c=>{$('#page-schedule').innerHTML=ui.events.filter(e=>e.cycle===c).map(e=>`<article class="schedule-row"><div class="schedule-date">${e.day}<small>SEP 2026</small></div><div><h3>${e.name}</h3><p>Domingo · ${e.time} · Lima (UTC−5)</p></div></article>`).join('')};$$('#page-cycles button').forEach(b=>b.onclick=()=>{$$('#page-cycles button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(b.dataset.c)});render('pre');renderFijas($('#cepre-fijas'),data);if(new URLSearchParams(location.search).get('panel')==='fijas'||pathName()==='/fijas-cepreuni')requestAnimationFrame(()=>$('#cepre-fijas').scrollIntoView({block:'start'}))}
const EVALUATIONS=[{name:'1RA PC',range:[1,2]},{name:'2DA PC',range:[3,6]},{name:'1ER PARCIAL',range:[1,7]},{name:'3RA PC',range:[8,9]},{name:'4TA PC',range:[10,11]},{name:'2DO PARCIAL',range:[8,13]},{name:'5TA PC',range:[15,16]},{name:'6TA PC',range:[17,18]},{name:'7MA PC',range:[19,20]},{name:'EXAMEN FINAL',range:[15,20]}];
const HUMANITIES=new Set(['razonamientoverbal','razonamientomatematico','historia','geografia','economia','lenguaje','literatura','filosofia','dpcc','logica','psicologia','ingles']);
const AREAS=[['Matemática',['aritmetica','algebra','geometria','trigonometria','calculo']],['Ciencias',['fisica','quimica']],['Humanidades',['razonamientoverbal','razonamientomatematico','historia','geografia','economia','lenguaje','literatura','filosofia','dpcc','logica','psicologia','ingles']]];
const weekNum=label=>{const m=/\d+/.exec(label||'');return m?+m[0]:null};
// El temario cubre tres procesos distintos y antes vivían mezclados: Admisión UNI y CEPREUNI compartían
// un selector escondido dentro de los filtros, y San Marcos —cuyo temario sí existe en el repositorio—
// no aparecía en ninguna parte. Ahora cada proceso es su propia sección.
function syllabus(out){const temarios=data.syllabus.temarios;const marcos=data.syllabus.sanMarcos;const progress=store.get('topics',{});
 const SECTIONS=[['admission','Admisión UNI'],['cepre','CEPREUNI'],['marcos','Admisión San Marcos']];
 const marcosGroups=marcos?[...new Set(marcos.courses.map(c=>c.group))]:[];
 out.innerHTML=`<div class="p-chips" id="syllabus-section">${SECTIONS.map(([id,label],i)=>`<button data-section="${id}" aria-pressed="${i===0}">${esc(label)}</button>`).join('')}</div><div class="p-chips" id="cepre-view" hidden><button data-view="course" aria-pressed="true">Por curso</button><button data-view="exam" aria-pressed="false">Por evaluación</button></div><div id="syllabus-course"><div class="p-filter"><input class="p-input" id="topic-query" type="search" placeholder="Buscar un concepto dentro del curso…" aria-label="Buscar tema"><select class="p-select" id="topic-course" aria-label="Curso">${AREAS.map(([area,ids])=>`<optgroup label="${esc(area)}">${ids.map(id=>`<option value="${id}">${esc(temarios[id].name)}</option>`).join('')}</optgroup>`).join('')}</select></div><div class="p-split"><div><p class="p-result" id="topic-count" aria-live="polite"></p><div class="topic-list" id="topics"></div></div><aside><div class="p-panel"><span class="p-label">TU MAPA DE PROGRESO</span><h2 id="topic-progress" style="margin-top:18px"></h2><div class="progress-line"><i id="topic-progress-bar"></i></div><p>Marca los conceptos que ya revisaste. No es una evaluación: tú decides cuándo estás listo para practicar.</p>${internal('/clases','Buscar una explicación','text-button')}<p class="source-note">Progreso guardado en este navegador. No sincronizado con tu cuenta.</p></div><div class="p-notice" id="syllabus-source"></div></aside></div></div><div id="syllabus-exam" hidden><div class="p-subhead"><div><span class="p-label">CEPREUNI / EVALUACIONES</span><h2>¿Qué entra en tu próxima prueba?</h2></div></div><div class="p-chips" id="exam-picker">${EVALUATIONS.map((e,i)=>`<button data-exam="${i}" aria-pressed="${i===0}">${esc(e.name)}</button>`).join('')}</div><p class="p-notice" id="exam-range"></p><div id="exam-results"></div></div><div id="syllabus-marcos" hidden>${marcos?`<div class="p-subhead"><div><span class="p-label">UNMSM / CICLO ${esc(marcos.cycle)}</span><h2>Temario de Admisión San Marcos</h2></div><span>${marcos.courses.length} cursos</span></div><div class="p-filter"><input class="p-input" id="marcos-query" type="search" placeholder="Buscar un tema del temario San Marcos…" aria-label="Buscar tema de San Marcos"><select class="p-select" id="marcos-course" aria-label="Curso">${marcosGroups.map(g=>`<optgroup label="${esc(g)}">${marcos.courses.filter(c=>c.group===g).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</optgroup>`).join('')}</select></div><p class="p-result" id="marcos-count" aria-live="polite"></p><div class="topic-list" id="marcos-topics"></div><p class="source-note">Temario publicado para el proceso de admisión UNMSM. Consulta el prospecto oficial para cambios del proceso.</p>`:empty('El temario de San Marcos no está disponible.')}</div>`;
 let section='admission',view='course',shown=[];
 const render=()=>{const id=$('#topic-course').value,c=temarios[id],track=section==='cepre'?'cepre':'admission',modules=track==='cepre'?c.cepreSemanas:c.semanas;let n=0;const rows=(modules||[]).flatMap(m=>(m.topics||[]).map(t=>({...t,group:m.label,key:`${id}/${track}/${n++}`})));const q=norm($('#topic-query').value);shown=rows;const filtered=rows.filter(t=>norm(t.title+' '+t.items.join(' ')).includes(q));$('#topic-count').textContent=`${c.name} · ${filtered.length} temas`;$('#topics').innerHTML=filtered.map((t,i)=>`<details class="topic-item"><summary><span class="topic-num">${String(i+1).padStart(2,'0')}</span><span>${esc(t.title.replace(/^\d+\.\s*/,''))}</span><span class="topic-plus">+</span></summary><div class="topic-detail"><span class="p-label">${esc(t.group)}</span>${t.items.map(x=>`<p>${esc(x)}</p>`).join('')}<label><input type="checkbox" data-topic="${esc(t.key)}" ${progress[t.key]?'checked':''}>Ya revisé este concepto</label></div></details>`).join('')||empty('No se encontraron temas en este programa.');$('#syllabus-source').textContent=track==='cepre'?'Programa del ciclo CEPREUNI, semana por semana. Consulta la guía oficial para cambios del ciclo.':'Temario del prospecto de Admisión UNI. Se conserva el contenido completo de cada tema.';$$('#topics [data-topic]').forEach(el=>el.onchange=()=>{progress[el.dataset.topic]=el.checked;if(!store.set('topics',progress))toast('El navegador no permitió guardar el progreso.');update()});update()};
 const update=()=>{const done=shown.filter(t=>progress[t.key]).length;$('#topic-progress').textContent=`${done} / ${shown.length} temas`;$('#topic-progress-bar').style.width=(shown.length?done/shown.length*100:0)+'%'};
 $('#topic-query').oninput=render;$('#topic-course').onchange=render;
 const renderMarcos=()=>{if(!marcos)return;const c=marcos.courses.find(x=>x.id===$('#marcos-course').value)||marcos.courses[0];const q=norm($('#marcos-query').value);const hits=c.topics.map((t,i)=>({text:t,key:`marcos/${c.id}/${i}`})).filter(t=>norm(t.text).includes(q));$('#marcos-count').textContent=`${c.name} · ${hits.length} temas`;$('#marcos-topics').innerHTML=hits.map((t,i)=>`<details class="topic-item"><summary><span class="topic-num">${String(i+1).padStart(2,'0')}</span><span>${esc(t.text.split('. ')[0].slice(0,90))}</span><span class="topic-plus">+</span></summary><div class="topic-detail"><span class="p-label">${esc(c.group)}</span><p>${esc(t.text)}</p><label><input type="checkbox" data-topic="${esc(t.key)}" ${progress[t.key]?'checked':''}>Ya revisé este concepto</label></div></details>`).join('')||empty('No se encontraron temas con esa búsqueda.');$$('#marcos-topics [data-topic]').forEach(el=>el.onchange=()=>{progress[el.dataset.topic]=el.checked;store.set('topics',progress)})};
 if(marcos){$('#marcos-query').oninput=renderMarcos;$('#marcos-course').onchange=renderMarcos}
 let examIndex=0;const renderExam=()=>{const ev=EVALUATIONS[examIndex];$$('#exam-picker [data-exam]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.exam===examIndex)));$('#exam-range').textContent=`Semanas ${ev.range[0]}–${ev.range[1]} del ciclo CEPREUNI · Humanidades acumula desde la semana 1 hasta la ${ev.range[1]}.`;const cards=Object.entries(temarios).map(([id,c])=>{const modules=c.cepreSemanas||[];const inRange=HUMANITIES.has(id)?modules.filter(m=>{const w=weekNum(m.label);return w!==null&&w<=ev.range[1]}):modules.filter(m=>{const w=weekNum(m.label);return w!==null&&w>=ev.range[0]&&w<=ev.range[1]});const topics=inRange.flatMap(m=>(m.topics||[]).map(t=>({...t,group:m.label})));if(!topics.length)return '';return `<details class="topic-item exam-course"><summary><span>${esc(c.name)}</span><span class="topic-plus">${topics.length}</span></summary><div class="topic-detail">${topics.map(t=>`<p><b>${esc(t.group)}</b> · ${esc(t.title.replace(/^\d+\.\s*/,''))}</p>`).join('')}${HUMANITIES.has(id)?'<p class="source-note">Acumulativo: incluye todas las semanas previas del ciclo.</p>':''}</div></details>`}).filter(Boolean).join('');$('#exam-results').innerHTML=cards||empty('No hay temario CEPREUNI registrado para este rango todavía.')};
 $$('#exam-picker [data-exam]').forEach(b=>b.onclick=()=>{examIndex=+b.dataset.exam;renderExam()});
 const show=()=>{const courseOpen=section==='admission'||(section==='cepre'&&view==='course');$('#syllabus-course').hidden=!courseOpen;$('#syllabus-exam').hidden=!(section==='cepre'&&view==='exam');$('#syllabus-marcos').hidden=section!=='marcos';$('#cepre-view').hidden=section!=='cepre';if(courseOpen)render();if(section==='marcos')renderMarcos()};
 $$('#syllabus-section [data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;$$('#syllabus-section [data-section]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));show()});
 $$('#cepre-view [data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$$('#cepre-view [data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));show()});
 show();renderExam();
}
function buildPlan(profile){
 const {focus,days,start,weeks,blocksPerDay}=profile;
 const weights={};AREAS.forEach(([name])=>weights[name]=name===focus?3:1);
 const pools={};AREAS.forEach(([name,ids])=>{pools[name]=ids.map(id=>{const c=data.syllabus.temarios[id];const mods=c.cepreSemanas||c.semanas||[];const topics=mods.flatMap(m=>(m.topics||[]).map(t=>({group:m.label,title:t.title.replace(/^\d+\.\s*/,'')})));return {id,name:c.name,topics,pos:0}})});
 const cursor={};AREAS.forEach(([name])=>cursor[name]=0);
 const counts={};AREAS.forEach(([name])=>counts[name]=0);
 function nextForArea(name){const courses=pools[name];for(let tries=0;tries<courses.length;tries++){const idx=cursor[name]%courses.length;cursor[name]++;const course=courses[idx];if(course.pos<course.topics.length){const t=course.topics[course.pos++];return {area:name,courseId:course.id,course:course.name,group:t.group,title:t.title,type:'study'}}}
  courses.forEach(c=>c.pos=0);const idx=cursor[name]%courses.length;cursor[name]++;const course=courses[idx];const t=course.topics[course.pos++%course.topics.length]||{group:'',title:course.name};return {area:name,courseId:course.id,course:course.name,group:t.group,title:'Repaso: '+t.title,type:'review'}}
 const entries=[];const startDate=new Date(start+'T00:00:00');
 for(let d=0;d<weeks*7;d++){const date=new Date(startDate);date.setDate(date.getDate()+d);const weekday=date.getDay();if(weekday===0||!days.includes(weekday))continue;
  for(let b=0;b<blocksPerDay;b++){const areaNames=AREAS.map(([n])=>n).sort((a,c)=>counts[a]/weights[a]-counts[c]/weights[c]);const area=areaNames[0];counts[area]++;const pick=nextForArea(area);const iso=date.toISOString().slice(0,10);entries.push({date:iso,index:b,...pick,done:false,id:iso+'-'+b})}}
 return entries;
}
function planWeekStart(iso){const d=new Date(iso+'T00:00:00');const day=d.getDay()||7;d.setDate(d.getDate()-(day-1));return d}
function planner(out){
 let plan=store.get('plan',null);
 out.innerHTML=`<div class="p-panel plan-setup" id="plan-setup"><div class="p-row"><div><span class="p-label">TU TRAYECTORIA / CONFIGURA TU PLAN</span><h2 style="margin-top:12px">Genera tu horario de estudio.</h2></div></div><p class="source-note">Elige tu enfoque y tu disponibilidad. Distribuimos tus cursos por área, en el orden real del temario CEPREUNI, y damos prioridad a la que más peso tenga.</p><div class="plan-fields"><label>Dale prioridad a<select id="plan-focus" class="p-select">${AREAS.map(([n])=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}<option value="balanced">Equilibrado</option></select></label><label>Empieza el<input class="p-input" type="date" id="plan-start"></label><label>Duración<select id="plan-weeks" class="p-select"><option value="2">2 semanas</option><option value="4" selected>4 semanas</option><option value="8">8 semanas</option></select></label><label>Bloques por día<select id="plan-blocks" class="p-select"><option value="1">1</option><option value="2" selected>2</option><option value="3">3</option></select></label></div><div class="plan-days" id="plan-days">${[['1','L'],['2','M'],['3','X'],['4','J'],['5','V'],['6','S']].map(([v,l])=>`<label><input type="checkbox" value="${v}" checked>${l}</label>`).join('')}</div><button class="button primary" id="plan-generate" type="button">Generar mi plan</button></div><div id="plan-calendar" hidden><div class="p-row" style="margin:28px 0 14px"><div><span class="p-label">TU SEMANA</span><h2 style="margin-top:8px" id="plan-week-label"></h2></div><div class="p-chips"><button id="plan-prev" type="button">← Semana</button><button id="plan-next" type="button">Semana →</button><button id="plan-reset" class="text-button" type="button">Reconfigurar</button></div></div><p class="p-result" id="plan-progress-label" aria-live="polite"></p><div class="progress-line"><i id="plan-progress-bar"></i></div><div class="plan-week" id="plan-week"></div><p class="source-note">Tu plan y tu avance se guardan solo en este navegador. Puedes reconfigurarlo cuando quieras; no se comparte ni se sincroniza con tu cuenta.</p></div><a class="button account-cloud-link" href="/planificador/seguimiento">Mi seguimiento y calendario →</a>${sub('¿No sabes por dónde empezar?')}<div class="p-grid two">${tile('/temario','Tu mapa de conceptos','Explora los temas antes de organizar tus sesiones.','list')}${tile('/fijas-cepreuni','Prepara tu Primera PC','Consulta los tipos de problema del modelo histórico.','target')}</div>`;
 const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());$('#plan-start').value=today.toISOString().slice(0,10);
 let weekOffset=0;
 const dayNames=['Domingo','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado'];
 const renderWeek=()=>{
  const base=planWeekStart(plan.profile.start);const start=new Date(base);start.setDate(start.getDate()+weekOffset*7);
  const end=new Date(start);end.setDate(end.getDate()+6);
  const fmt=d=>d.toLocaleDateString('es-PE',{day:'numeric',month:'short'});
  $('#plan-week-label').textContent=`${fmt(start)} – ${fmt(end)}`;
  $('#plan-prev').disabled=weekOffset<=0;
  const done=plan.entries.filter(e=>e.done).length;
  $('#plan-progress-label').textContent=`${done} / ${plan.entries.length} bloques completados`;
  $('#plan-progress-bar').style.width=(plan.entries.length?done/plan.entries.length*100:0)+'%';
  const cells=[];for(let i=0;i<7;i++){const d=new Date(start);d.setDate(d.getDate()+i);const iso=d.toISOString().slice(0,10);const items=plan.entries.filter(e=>e.date===iso);cells.push({iso,label:dayNames[d.getDay()],date:fmt(d),items,isSunday:d.getDay()===0})}
  $('#plan-week').innerHTML=cells.map(c=>`<div class="plan-day${c.items.length?'':' plan-day-empty'}"><header><b>${c.label}</b><span>${c.date}</span></header>${c.items.length?c.items.map(it=>`<label class="plan-block ${it.type==='review'?'is-review':''}"><input type="checkbox" data-block="${esc(it.id)}" ${it.done?'checked':''}><span class="p-label">${esc(it.area)}</span><b>${esc(it.course)}</b><small>${esc(it.group)} · ${esc(it.title)}</small></label>`).join(''):`<p class="source-note">${c.isSunday?'Descanso':'Sin bloques'}</p>`}</div>`).join('');
  $$('[data-block]').forEach(cb=>cb.onchange=()=>{const entry=plan.entries.find(e=>e.id===cb.dataset.block);if(entry)entry.done=cb.checked;store.set('plan',plan);renderWeek()});
 };
 const showCalendar=()=>{$('#plan-setup').hidden=true;$('#plan-calendar').hidden=false;weekOffset=0;renderWeek()};
 if(plan&&plan.entries?.length){showCalendar()}
 $('#plan-generate').onclick=()=>{
  const focus=$('#plan-focus').value,start=$('#plan-start').value||today.toISOString().slice(0,10),weeks=+$('#plan-weeks').value,blocksPerDay=+$('#plan-blocks').value;
  const days=$$('#plan-days input:checked').map(i=>+i.value);
  if(!days.length){toast('Elige al menos un día disponible.');return}
  const profile={focus,start,weeks,blocksPerDay,days};
  const entries=buildPlan(profile);
  plan={profile,entries,createdAt:new Date().toISOString()};
  if(!store.set('plan',plan))toast('No se pudo guardar el plan en este navegador.');
  toast('Tu plan se generó a partir del temario real.');
  showCalendar();
 };
 $('#plan-prev').onclick=()=>{if(weekOffset>0){weekOffset--;renderWeek()}};
 $('#plan-next').onclick=()=>{weekOffset++;renderWeek()};
 $('#plan-reset').onclick=()=>{$('#plan-calendar').hidden=true;$('#plan-setup').hidden=false};
}
function fixed(out){renderFijas(out,data)}
// Small arithmetic parser. No eval, Function constructor, or remote requests.
export function calculate(input){const text=input.replace(/\s+/g,'').replace(/×/g,'*').replace(/÷/g,'/').replace(/,/g,'.');if(!text||text.length>160||/[^0-9.+\-*/()%]/.test(text))throw Error('Expresión no válida');const tokens=text.match(/(?:\d+(?:\.\d*)?|\.\d+)|[+\-*/()%]/g)||[];if(tokens.join('')!==text)throw Error('Número no válido');let at=0,depth=0;function value(){if(++depth>40)throw Error('Expresión demasiado larga');let n;if(tokens[at]==='+'||tokens[at]==='-'){const sign=tokens[at++];n=(sign==='-'?-1:1)*value()}else if(tokens[at]==='('){at++;n=add();if(tokens[at++]!==')')throw Error('Falta cerrar paréntesis')}else{const t=tokens[at++];if(!t||!/^\d|^\./.test(t))throw Error('Falta un número');n=Number(t)}while(tokens[at]==='%'){at++;n/=100}depth--;return n}function mul(){let n=value();while(['*','/'].includes(tokens[at])){const op=tokens[at++],v=value();if(op==='/'&&v===0)throw Error('No se puede dividir entre cero');n=op==='*'?n*v:n/v}return n}function add(){let n=mul();while(['+','-'].includes(tokens[at])){const op=tokens[at++],v=mul();n=op==='+'?n+v:n-v}return n}const result=add();if(at!==tokens.length||!Number.isFinite(result))throw Error('Revisa la expresión');return Number(result.toPrecision(12))}
function calculator(out){renderScore(out,data)}
function admissions(out){out.innerHTML=`<section class="p-panel p-feature"><div><span class="p-label">UNIVERSIDAD NACIONAL DE INGENIERÍA</span><h2>Una meta grande.<br>Decisiones informadas.</h2><p>Organiza tu preparación sin confundir una referencia histórica con un resultado asegurado.</p><div class="page-actions">${link('https://admision.uni.edu.pe/','Consultar Admisión UNI','button primary',true)}</div></div>${orbit()}</section>${sub('Conecta tu preparación')}<div class="p-grid">${tile('/temario','Temario de admisión','Revisa el alcance completo por curso.','list')}${tile('/planificador','Plan de preparación','Organiza temas y sesiones.','calendar')}${tile('/simulacros','Práctica y evaluación','Explora tus siguientes desafíos.','target')}</div>${sub('Información del proceso')}<div class="p-panel">${link('/admision','Carreras, referencias de corte y análisis de admisión','link-line',true)}${link('/resultados-admision','Resultados de admisión','link-line',true)}${link('https://admision.uni.edu.pe/','Cronograma, requisitos y comunicados oficiales','link-line',true)}</div>${note('No se muestran puntajes, vacantes o fechas de admisión inventadas. La información que cambia con el proceso se consulta en su fuente vigente.')}`}
function practice(out,p){out.innerHTML=`<div class="p-split"><section class="p-panel"><span class="p-label">PREPARA TU EVALUACIÓN</span><h2 style="margin-top:16px">Elige un punto de partida.</h2><label class="p-label" for="practice-eval">Evaluación</label><select id="practice-eval" class="p-select" style="display:block;width:100%;margin-top:12px">${data.syllabus.evaluations.map((e,i)=>`<option value="${i}">${esc(e.name)}</option>`).join('')}</select><div id="practice-scope"></div><div class="page-actions">${internal('/temario','Explorar estos cursos','button primary')}${internal('/fijas-cepreuni','Fijas Primera PC','text-button')}</div></section><aside class="p-panel"><span class="p-label">SERVICIO CONECTADO</span><h2 style="margin-top:17px">Practica en el motor original.</h2><p>La generación con IA, el banco privado y la calificación requieren el servicio real. Esta vista de diseño no realiza llamadas ni consume créditos.</p>${link('https://universetostudy.com'+p,p==='/simulacros'?'Abrir simulador original':'Abrir archivo original','button',true)}<p class="source-note">Al continuar, sales de la vista previa local.</p></aside></div>${sub('Todo listo para prepararte')}<div class="p-grid">${tile('/cepreuni/ciclopre20271','Material del ciclo','Abre los documentos y libros disponibles.','layers')}${tile('/clases','Revisar una explicación','Encuentra videos del curso.','play')}${tile('/planificador','Organizar el repaso','Lleva tus temas a tu planificador.','calendar')}</div>`;const render=()=>{const e=data.syllabus.evaluations[Number($('#practice-eval').value)];$('#practice-scope').innerHTML=`<p class="p-notice">${e.range?'Semanas '+e.range.join(' a '):'Alcance del temario'}</p><div class="p-chips">${(e.subjects||[]).map(s=>`<span class="p-chip">${esc(s)}</span>`).join('')}</div>`};$('#practice-eval').onchange=render;render()}
function account(out){renderProfile(out,data,ui.openPreferences)}
function community(out,p){const channels=[['https://whatsapp.com/channel/0029VbBKG4SAojYveJl8MJ0T','WhatsApp','Avisos y novedades de la comunidad.','message'],['https://www.youtube.com/@universepre_official','YouTube','Contenido del canal de Universe.','play'],['https://www.tiktok.com/@universe_preuni','TikTok','Universe en formato breve.','play'],['https://linktr.ee/universetostudy','Linktree','Todos los enlaces, reunidos.','grid']];out.innerHTML=`<section class="p-panel p-feature"><div><span class="p-label">UNA COMUNIDAD, MUCHAS CONEXIONES</span><h2>Tu curiosidad<br>no está sola.</h2><p>Conecta con los canales de Universe. Sin conversaciones, mensajes ni usuarios ficticios en la demostración.</p><div class="page-actions">${link('/unitalk','Entrar a UNITALK','button primary',true)}</div></div>${orbit()}</section>${sub('Nuestros canales')}${brandRow(data.logos)}<div class="p-grid two">${channels.map(([u,t,d,i])=>tile(u,t,d,i,'Abrir canal original',true)).join('')}</div>${sub('¿Necesitas ayuda?')}<div class="p-panel">${link('https://wa.me/51963385410?text=Hola%2C%20necesito%20ayuda%20con%20Universe%20to%20Study','Contactar con soporte de Universe','link-line',true)}</div>`}
function connected(out,p){const isRank=p==='/ranking';out.innerHTML=`<div class="p-split"><section class="p-panel"><span class="p-label">${isRank?'RESULTADOS CON IDENTIDAD':'ORGANIZACIÓN DEL CICLO'}</span><h2 style="margin-top:17px">${isRank?'Lo importante es tu progreso.':'Un lugar para cada clase.'}</h2><p>${isRank?'Consulta el ranking y tus resultados reales en el servicio conectado. No se presentan posiciones ni estudiantes de ejemplo como si fueran datos reales.':'La guía de docentes, salones y horarios necesita los datos vigentes del ciclo. Para no mostrar información desactualizada, la consulta se realiza en su fuente original.'}</p><div class="page-actions">${link('https://universetostudy.com'+p,isRank?'Consultar ranking real':'Abrir guía de aulas','button primary',true)}</div>${note('Esta pantalla muestra el nuevo formato. La cuenta y los datos en vivo se mantienen en la plataforma original.')}</section><aside class="p-panel">${orbit()}<span class="p-label">EL SIGUIENTE PASO DEPENDE DE TI</span>${internal(isRank?'/planificador':'/cepreuni',isRank?'Organizar mi avance':'Volver a mi ciclo','link-line')}</aside></div>${sub('Sigue conectado')}<div class="p-grid two">${tile('/temario','Revisar mis conceptos','Continúa tu preparación con el temario.','list')}${tile('/cepreuni/ciclopre20271','Materiales del ciclo','Recursos para tu próxima sesión.','layers')}</div>`}
function information(out,p){const content={
 '/nosotros':[['Aprender, practicar, conectar.','Universe reúne herramientas de preparación, recursos y comunidad para estudiantes que quieren avanzar. El espacio conecta temarios, clases, bibliotecas, planificación y evaluaciones.'],['Una comunidad independiente.','Universe no se presenta como una página oficial de la UNI o de CEPREUNI. Los enlaces institucionales se diferencian de los materiales y herramientas de la comunidad.']],
 '/metodologia-editorial':[['La fuente permanece visible.','Los libros mantienen su portada, título, autor y enlace de origen. Los materiales próximos no se muestran como si estuvieran disponibles.'],['No todo dato es una garantía.','Las fijas se identifican como un modelo histórico. Las fechas requieren confirmar cambios con la institución y los resultados en vivo se consultan en la plataforma conectada.']],
 '/correcciones':[['Cuéntanos dónde ocurre.','Indica el curso, título del material, página o enlace y describe el error. Si es posible, incluye el fragmento que debería revisarse.'],['Envía el reporte por el canal real.','Esta propuesta no incluye un formulario que envíe datos sin una conexión configurada. Puedes contactar con soporte usando el enlace de abajo.']],
 '/terminos':[['Consulta la versión vigente.','El rediseño no sustituye ni reescribe los términos publicados. Las condiciones legales completas permanecen en la página original.'],['Sobre esta demostración.','Los enlaces de recursos abren sitios externos. No se solicitan contraseñas, no se generan respuestas con IA y no se modifica la información de tu cuenta.']],
 '/privacidad':[['Lo que se guarda aquí.','Tus preferencias, las tareas del planificador y las marcas de temas estudiados se guardan en el almacenamiento local de este navegador. No se envían a Universe desde esta demostración.'],['Lo que se conecta fuera.','Al pulsar un recurso externo se abre su proveedor: Universe, Google Drive, YouTube o un canal de la comunidad. Esos servicios aplican sus propias condiciones y políticas de privacidad.']]};out.innerHTML=`<article class="p-panel info-prose">${(content[p]||[]).map(([h,t])=>`<h2>${h}</h2><p>${t}</p>`).join('')}<div class="page-actions">${link('https://universetostudy.com'+p,'Consultar página original','button',true)}${internal('/contacto','Contactar','text-button')}</div></article>`}
export function startPlatform(api){ui=api;home=$('main');const shell=document.createElement('main');shell.id='platform';shell.className='platform';shell.hidden=true;shell.innerHTML='<aside class="side-rail"></aside><div class="platform-body"></div>';home.after(shell);view=$('.platform-body');const phone=document.createElement('a');phone.className='phone-nav';phone.href='/explorar';phone.textContent='Explorar toda la plataforma →';$('.hero-copy').append(phone);$('#search-dialog .dialog-foot').removeAttribute('data-en');$('#search-dialog .dialog-foot').textContent='Busca herramientas, materiales y recursos de estudio.';
 // Real local URLs also make Ctrl-click, copying links and opening new tabs work.
 const localize=()=>{$$('a[href]').forEach(a=>{if(a.hasAttribute('data-live'))return;let u;try{u=new URL(a.getAttribute('href'),location.origin)}catch{return}const p=u.pathname.replace(/\/$/,'').replace(/\.html$/,'')||'/';if(['universetostudy.com','www.universetostudy.com'].includes(u.hostname)&&routes[p]){a.setAttribute('href',p+u.search+u.hash);a.removeAttribute('target')}})};
 localize();new MutationObserver(localize).observe(document.body,{childList:true,subtree:true});
 $('.skip-link').addEventListener('click',e=>{e.preventDefault();const target=home.hidden?$('#page-title'):home;target?.scrollIntoView({behavior:'instant'});target?.focus({preventScroll:true})});
 const go=async(url)=>{$$('dialog[open]').forEach(d=>d.close());const u=new URL(url,location.origin);history.pushState({},'',u.pathname+u.search+u.hash);await route(true);scrollTo({top:0,behavior:'instant'});if(u.hash)setTimeout(()=>{try{$(u.hash)?.scrollIntoView({behavior:'instant'})}catch{}},60)};
 document.addEventListener('click',e=>{const anchor=e.target.closest('a[href]');if(anchor){const target=new URL(anchor.href,location.href);if(["/account/cloud","/planificador/seguimiento","/simulacros","/ranking","/admision","/docentes-cepreuni","/informacion-cepreuni","/privacidad","/terminos","/nosotros","/metodologia-editorial","/correcciones","/contacto","/aula","/biblioteca/recursos","/autores/criss-vasquez","/autores/luhana-belen","/biblioteca/seleccion-de-preguntas","/calculadora-admision","/fichas-admision","/guias/como-interpretar-ranking-cepreuni","/guias/como-se-calcula-puntaje-cepreuni-2026-2","/ingresantes-cepreuni","/ingresantes-uni-2026-2","/ranking-admision","/resultados-admision"].includes(target.pathname.replace(/\/$/,'')))return;}if(e.defaultPrevented||e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;const a=e.target.closest('a');if(!a||a.hasAttribute('data-live')||a.hasAttribute('download'))return;const href=a.getAttribute('href');if(!href||href==='data:,')return;let u;try{u=new URL(href,location.href)}catch{return}if(u.origin!==location.origin&&!['universetostudy.com','www.universetostudy.com'].includes(u.hostname))return;const p=u.pathname.replace(/\/$/,'').replace(/\.html$/,'')||'/';if(p!=='/'&&!routes[p])return;e.preventDefault();if(p==='/'&&pathName()==='/'&&u.hash){$(u.hash)?.scrollIntoView({behavior:'smooth'});return}go(p+u.search+u.hash)});
 addEventListener('popstate',()=>route());route();return{navigate:go};
}
