const KEY='universe-preview-profile';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const profile=()=>read(KEY,null);
const tones=['blue','silver','violet','amber'];
const googleIcon='<svg viewBox="0 0 24 24" width="19" height="19" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.2c0-.7-.1-1.4-.2-2.2H12v4.2h5.4a4.6 4.6 0 0 1-2 3v2.6h3.3c1.9-1.8 2.9-4.4 2.9-7.6Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.6c-.9.6-2 .9-3.4.9-2.6 0-4.9-1.8-5.7-4.2H2.9v2.7A10.1 10.1 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.3 13.7a6 6 0 0 1 0-3.4V7.6H2.9a10 10 0 0 0 0 8.8l3.4-2.7Z"/><path fill="#EA4335" d="M12 6.1c1.5 0 2.8.5 3.8 1.5l2.8-2.8A9.5 9.5 0 0 0 12 2a10.1 10.1 0 0 0-9.1 5.6l3.4 2.7A6 6 0 0 1 12 6.1Z"/></svg>';
const googleLink=()=>`<button class="google-signin" type="button" data-google-signin>${googleIcon}<span>Continuar con Google</span></button>`;
export function syncProfileBadge(){const p=window.UniverseGoogleAuth?.user()||profile(),a=document.querySelector('.header .account');if(!a)return;const name=p?.name||'Mi perfil',tone=tones.includes(p?.tone)?p.tone:'blue';a.setAttribute('aria-label',p?'Abrir perfil de '+name:'Entrar o registrarme');a.innerHTML=`<span class="profile-mini tone-${tone}" aria-hidden="true">${esc(p?name.charAt(0).toUpperCase():'U')}</span><span data-en="${esc(p?name:'My profile')}" data-es="${esc(name)}">${esc(name)}</span>`;a.href='/account'}
export function renderProfile(out,data,openPreferences){
 if(window.UniverseGoogleAuth?.user()){out.innerHTML='<section class="p-panel"><h2>Tu cuenta está conectada.</h2><p>Gestiona tu perfil, tus preferencias y tu comunidad.</p><a class="button primary" href="/account/cloud">Abrir mi perfil →</a><button class="button" id="account-logout">Cerrar sesión</button></section>';out.querySelector('#account-logout').onclick=()=>{window.UniverseGoogleAuth.signOut();renderProfile(out,data,openPreferences)};return}let p=profile();const $=s=>out.querySelector(s),status=msg=>{const el=$('#profile-status');if(el)el.textContent=msg};
 function save(next){try{localStorage.setItem(KEY,JSON.stringify(next));p=next;syncProfileBadge();return true}catch{status('El navegador no permitió guardar el perfil. Revisa el almacenamiento.');return false}}
 if(!p){out.innerHTML=`<section class="profile-entry"><div class="p-panel entry-welcome"><span class="p-label">UNIVERSE / TU IDENTIDAD</span><div class="profile-emblem" aria-hidden="true">U<span></span><i></i></div><h2>Tu camino.<br>Tu propio espacio.</h2><p>Organiza tus temas, guarda tus planes y personaliza la experiencia desde un perfil.</p><div class="profile-benefits"><span>01 · Una meta definida</span><span>02 · Tus preferencias</span><span>03 · Tu progreso local</span></div></div><div class="p-panel entry-form"><span class="p-label">ENTRAR O REGISTRARME</span><h2>Empieza a tu manera.</h2>${googleLink()}<p class="source-note">Tu identidad se verifica con Google. Universe nunca recibe tu contraseña.</p><div class="entry-separator"><span></span>o continúa aquí<span></span></div><form id="guest-form"><label for="guest-name">¿Cómo te llamamos?</label><input class="p-input" id="guest-name" type="text" maxlength="40" placeholder="Tu nombre o alias" autocomplete="nickname"><button class="button primary" type="submit">Crear perfil de invitado →</button></form><p class="source-note">Sin contraseña ni correo. Tu perfil de invitado y sus cambios se guardan únicamente en este navegador; no se sincronizan entre dispositivos.</p><p id="profile-status" role="status"></p><div class="entry-legal"><a href="/privacidad">Privacidad</a><a href="/terminos">Términos</a></div></div></section>`;
 $('#guest-form').onsubmit=e=>{e.preventDefault();if(save({name:$('#guest-name').value.trim().slice(0,40)||'Invitado',career:'C1',cycle:'2027-1',goal:'',tone:'blue',createdAt:new Date().toISOString(),provider:'guest'}))renderProfile(out,data,openPreferences)};return}
 const tasks=read('universe-preview-tasks',[]),topics=read('universe-preview-topics',{}),done=tasks.filter(t=>t.status==='done').length,checked=Object.values(topics).filter(Boolean).length,careerName=data.scores.careers.find(c=>c[0]===p.career)?.[1]||'Por elegir';const tone=tones.includes(p.tone)?p.tone:'blue';
 out.innerHTML=`<section class="p-panel profile-banner"><div class="profile-avatar tone-${tone}">${esc(p.name.charAt(0).toUpperCase())}</div><div><span class="p-label">PERFIL DE INVITADO · ESTE NAVEGADOR</span><h2 id="profile-display-name">${esc(p.name)}</h2><p>${esc(careerName)} · Ciclo ${esc(p.cycle)}</p></div><button id="profile-preferences" class="button">Preferencias</button></section><div class="p-statbar"><div><b>${tasks.length}</b><span>tareas en tu plan</span></div><div><b>${done}</b><span>tareas completadas</span></div><div><b>${checked}</b><span>temas marcados</span></div></div><div class="profile-layout"><section class="p-panel"><span class="p-label">TU PERFIL</span><h2>Hazlo tuyo.</h2><form id="profile-form"><label>Nombre o alias<input class="p-input" id="profile-name" maxlength="40" value="${esc(p.name)}" required autocomplete="nickname"></label><label>Tu carrera<select id="profile-career" class="p-select">${data.scores.careers.map(([c,n])=>`<option value="${esc(c)}" ${p.career===c?'selected':''}>${esc(n)}</option>`).join('')}</select></label><label>Ciclo<select id="profile-cycle" class="p-select">${['2027-2','2027-1','2026-2','2026-1','Preparación independiente'].map(v=>`<option ${p.cycle===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Tu siguiente objetivo<textarea class="p-input" id="profile-goal" rows="3" maxlength="240" placeholder="¿Qué quieres lograr esta semana?">${esc(p.goal)}</textarea></label><fieldset class="profile-tones"><legend>Color de tu avatar</legend>${tones.map(t=>`<label class="tone-${t}"><input type="radio" name="avatar-tone" value="${t}" ${tone===t?'checked':''}><span>${({blue:'Azul',silver:'Plata',violet:'Violeta',amber:'Ámbar'})[t]}</span></label>`).join('')}</fieldset><button class="button primary" type="submit">Guardar mi perfil →</button><p id="profile-status" role="status"></p></form></section><aside class="profile-aside"><section class="p-panel"><span class="p-label">TU SIGUIENTE PASO</span><h3>De la meta a la acción.</h3><p>${esc(p.goal||'Elige un tema y conviértelo en una tarea concreta.')}</p><a class="button" href="/planificador">Abrir mi plan →</a><a class="text-button" href="/calculadora">Calcular mi puntaje CEPREUNI →</a></section><section class="p-panel"><span class="p-label">CUENTA UNIVERSE</span><h3>Continúa con Google.</h3><p>Tu perfil de Google se guarda en tu cuenta. El perfil de invitado permanece en este dispositivo.</p>${googleLink()}</section><section class="p-panel"><span class="p-label">CONTROL DE TU PERFIL</span><p>Salir oculta tu perfil, pero conserva tu plan y los temas guardados en este dispositivo.</p><button id="profile-signout" class="text-button">Salir del perfil de invitado</button></section></aside></div>`;
 $('#profile-preferences').onclick=openPreferences;$('#profile-form').onsubmit=e=>{e.preventDefault();const name=$('#profile-name').value.trim();if(!name){status('Escribe un nombre o alias.');return}if(save({...p,name,career:$('#profile-career').value,cycle:$('#profile-cycle').value,goal:$('#profile-goal').value.trim(),tone:$('input[name="avatar-tone"]:checked').value})){renderProfile(out,data,openPreferences);status('Perfil guardado en este navegador.')}};
 $('#profile-signout').onclick=()=>{try{localStorage.removeItem(KEY)}catch{}syncProfileBadge();renderProfile(out,data,openPreferences)};
}

addEventListener('universe-google-auth',()=>{syncProfileBadge();if(location.pathname.replace(/\/$/,'')==='/account'&&window.UniverseGoogleAuth?.user())location.assign('/account/cloud')});
