import {labels,computeScore,requiredPercent,historyRows,cutoffMean} from './scores.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),num=(v,d=2)=>v===null||v===undefined?'—':Number(v).toLocaleString('es-PE',{maximumFractionDigits:d,minimumFractionDigits:d});
const external=(u,t)=>`<a href="${esc(u)}" data-live target="_blank" rel="noopener noreferrer">${esc(t)} ↗</a>`;
export const channels=[['uni','UNI','https://admision.uni.edu.pe/'],['cepreuni','CEPREUNI','https://www.cepre.uni.edu.pe/'],['youtube','YouTube','https://www.youtube.com/@universepre_official'],['whatsapp','WhatsApp','https://whatsapp.com/channel/0029VbBKG4SAojYveJl8MJ0T'],['drive','Google Drive','https://drive.google.com/drive/folders/12ShZq78aaBi6FYzwmTlGCudsgL76Eb93'],['tiktok','TikTok','https://www.tiktok.com/@universe_preuni'],['linktree','Linktree','https://linktr.ee/universetostudy']];
export function brandRow(logos,items=channels){return `<nav class="brand-rail" aria-label="Enlaces por logo">${items.map(([id,name,url])=>`<a class="brand-link brand-${id}" href="${esc(url)}" aria-label="${esc(name)}" title="${esc(name)}" ${url.startsWith('https:')?'data-live target="_blank" rel="noopener noreferrer"':''}><img src="${esc(logos[id])}" alt="${esc(name)}" width="160" height="64" loading="lazy"></a>`).join('')}</nav>`}
export const publishers=[['cepreuni','Materiales CEPREUNI','/cepreuni/ciclopre20271'],['universe','Editorial Universe','/biblioteca/universe'],['lumbreras','Lumbreras Editores','/biblioteca/lumbreras'],['cuzcano','Editorial Cuzcano','/biblioteca/cuzcano'],['uni','Libros universitarios','/biblioteca/librosuniversitarios']];
export const cepreEmblem=()=>'<div class="cepre-emblem" role="img" aria-label="Logo oficial de CEPREUNI"><span class="orbital-coordinate">CEPREUNI / CICLO 2027-1</span><div class="emblem-ring"><span class="emblem-ripple one"></span><span class="emblem-ripple two"></span><img src="/assets/home-access/cepreuni.png" alt="CEPREUNI"></div><span class="orbital-caption">Tu ciclo, tu ritmo.</span></div>';
export function renderCatalog(out,key,data){
 const books=data.catalogs[key].map(b=>b.section==='NUEVOS ARCHIVOS EN DRIVE'?{...b,section:b.title.startsWith('Solucionario')?'SOLUCIONARIOS':String(b.author||'OTROS MATERIALES').toUpperCase()}:b),groups=[...new Set(books.map(b=>b.catalog))],sections=[...new Set(books.map(b=>b.section))];
 const logo=key==='materials'?'cepreuni':key==='college'?'uni':key;
 out.innerHTML=`<div class="catalog-identity"><a href="/biblioteca" class="catalog-logo" title="Volver a las editoriales"><img src="${esc(data.logos[logo])}" alt="Logo original de ${esc(logo)}"></a><span>${groups.length} ${groups.length===1?'catálogo':'catálogos'}<br><small>${sections.length} secciones · ${books.length} recursos</small></span></div><div class="p-filter"><input id="catalog-query" class="p-input" type="search" placeholder="Buscar libro, curso o autor…" aria-label="Buscar en el catálogo"><select id="catalog-group" class="p-select" aria-label="Catálogo"><option value="">Todos los catálogos</option>${groups.map(t=>`<option>${esc(t)}</option>`).join('')}</select><select id="catalog-section" class="p-select" aria-label="Sección"><option value="">Todas las secciones</option></select></div><div class="catalog-options"><label><input id="catalog-ready" type="checkbox"> Solo disponibles</label><p id="catalog-count" class="p-result" aria-live="polite"></p></div><div id="book-results"></div><p class="source-note">Divisiones, portadas y enlaces conservados del catálogo. Los documentos abren en su fuente; «próximamente» no crea enlaces ficticios.</p>`;
 function sectionOptions(){const selected=$('#catalog-group').value;$('#catalog-section').innerHTML='<option value="">Todas las secciones</option>'+[...new Set(books.filter(b=>!selected||b.catalog===selected).map(b=>b.section))].map(s=>`<option>${esc(s)}</option>`).join('')}
 function book(b){const available=!!b.url&&!b.upcoming,id=(b.url||'').match(/\/d\/([^/?]+)|[?&]id=([^&]+)/),preview=(b.drivePreview||b.image==='/assets/library/editorials/cepreuni.png')&&id?`https://drive.google.com/thumbnail?id=${id[1]||id[2]}&sz=w1000`:b.image;return `<${available?'a':'article'} class="p-book" ${available?`href="${esc(b.url)}" data-live target="_blank" rel="noopener noreferrer"`:''}><div class="p-cover"><img src="${esc(preview)}" alt="Vista previa de ${esc(b.title)}" loading="lazy" width="180" height="240">${available?'':'<span class="book-badge">Próximamente</span>'}</div><span class="p-label">${esc(b.series)}</span><h4>${esc(b.title)}</h4><p>${esc(b.author)}</p><span class="book-action">${available?'Abrir documento ↗':'En preparación'}</span></${available?'a':'article'}>`}
 // Las clases del ciclo no están separadas por curso en los datos: el curso vive dentro de `series`
 // ("Trigonometría · Semana 1.2"). Sin separarlas, trigonometría, álgebra y física quedan mezcladas en
 // una sola lista. Cuando una sección reúne varios cursos, se subdivide; si es de un solo curso, no se
 // añade un nivel de jerarquía que no aporta nada.
 const courseOf=b=>(b.series||'').split('·')[0].trim();
 function courseBlocks(items){const courses=[...new Set(items.map(courseOf))].filter(Boolean);
  if(courses.length<2)return `<div class="p-books">${items.map(book).join('')}</div>`;
  return courses.map(c=>`<div class="catalog-course"><h4>${esc(c)}<small>${items.filter(b=>courseOf(b)===c).length}</small></h4><div class="p-books">${items.filter(b=>courseOf(b)===c).map(book).join('')}</div></div>`).join('')}
 function render(){const q=norm($('#catalog-query').value),g=$('#catalog-group').value,s=$('#catalog-section').value,ready=$('#catalog-ready').checked;const hits=books.filter(b=>(!g||b.catalog===g)&&(!s||b.section===s)&&(!ready||b.url&&!b.upcoming)&&norm([b.title,b.author,b.series,b.catalog,b.section].join(' ')).includes(q));const showing=hits;$('#catalog-count').textContent=`${hits.length} recursos · ${showing.length} visibles`;
 $('#book-results').innerHTML=[...new Set(showing.map(b=>b.catalog))].map((g,i)=>`<section class="catalog-volume"><header class="catalog-divider"><span>${String(groups.indexOf(g)+1).padStart(2,'0')} / CATÁLOGO</span><h2>${esc(g)}</h2><small>${hits.filter(b=>b.catalog===g).length} recursos</small></header>${[...new Set(showing.filter(b=>b.catalog===g).map(b=>b.section))].map(s=>`<section class="catalog-section"><h3><span></span>${esc(s)}<small>${hits.filter(b=>b.catalog===g&&b.section===s).length}</small></h3>${courseBlocks(showing.filter(b=>b.catalog===g&&b.section===s))}</section>`).join('')}</section>`).join('')||'<p class="p-empty">No hay recursos con estos filtros.</p>'}
 sectionOptions();['catalog-query','catalog-group','catalog-section','catalog-ready'].forEach(id=>$('#'+id).addEventListener(id==='catalog-query'?'input':'change',()=>{if(id==='catalog-group')sectionOptions();render()}));render();
}
export function renderFijas(out,data){
 const exams=data.fixedExams;
 let sortMode='original';
 out.innerHTML=`<div class="p-subhead"><div><span class="p-label">CEPREUNI / ARCHIVO DE FIJAS</span><h2>Elige tu evaluación.</h2></div></div><div class="p-filter"><select class="p-select" id="fixed-exam" aria-label="Evaluación de fijas">${exams.map((e,i)=>`<option value="${i}">${esc(e.label)}</option>`).join('')}</select><select class="p-select" id="fixed-course" aria-label="Curso de fijas"></select><input class="p-input" type="search" id="fixed-query" placeholder="Buscar tema o tipo de problema…" aria-label="Buscar fija"></div><div class="p-chips" id="fixed-sort"><button type="button" data-sort="original" aria-pressed="true">Orden del temario</button><button type="button" data-sort="frequency" aria-pressed="false">Más frecuentes primero</button></div><p class="p-notice" id="fixed-source"></p><p class="p-result" id="fixed-count" aria-live="polite"></p><div class="topic-list" id="fixed-list"></div>`;
 const freqOf=t=>t.problemType?Number(t.probability)||0:Number(t.total)||0;
 function courses(){const e=exams[+$('#fixed-exam').value];$('#fixed-course').innerHTML=e.courses.map((c,i)=>`<option value="${i}">${esc(c.name)}</option>`).join('');$('#fixed-source').textContent=e.probabilityModel?'Modelo probabilístico no oficial. '+e.sourceNote:`Registro histórico: ${e.range||e.periods?.join(' · ')||e.label}. La frecuencia en esta muestra no garantiza lo que vendrá en un examen.`}
 function render(){const e=exams[+$('#fixed-exam').value],c=e.courses[+$('#fixed-course').value],q=norm($('#fixed-query').value);let hits=c.topics.filter(t=>norm([t.name,t.focus,t.problemType].join(' ')).includes(q));if(sortMode==='frequency')hits=hits.map((t,i)=>[t,i]).sort((a,b)=>freqOf(b[0])-freqOf(a[0])||a[1]-b[1]).map(x=>x[0]);$('#fixed-count').textContent=`${e.label} · ${c.name} · ${hits.length} temas`;
 $('#fixed-list').innerHTML=hits.map((t,i)=>`<details class="topic-item"><summary><span class="topic-num">${String(i+1).padStart(2,'0')}</span><span>${esc(t.name)}</span><span class="topic-plus">+</span></summary><div class="topic-detail">${t.problemType?`<span class="p-label">TIPO DE PROBLEMA</span><p><strong>${esc(t.problemType)}</strong></p><p>${esc(t.focus)}</p><p>Muestra: ${esc(t.processes)} procesos. Estimación del modelo: ${esc(t.probability)}%.</p>`:`<span class="p-label">EVIDENCIA HISTÓRICA</span><p>${esc(t.total)} apariciones registradas${t.cycles?' en '+esc(t.cycles)+' ciclos':''}.</p>${t.counts?`<div class="frequency-row">${e.periods.map((p,j)=>`<span>${esc(p)}<b>${esc(t.counts[j]??0)}</b></span>`).join('')}</div>`:''}<p>La fuente identifica este tema, pero no describe un tipo de problema concreto. No se añade una descripción inventada.</p>`}<a class="text-button" href="/planificador?tema=${encodeURIComponent(t.name)}&curso=${encodeURIComponent(c.name)}">Llevarlo a mi plan →</a></div></details>`).join('')||'<p class="p-empty">No hay coincidencias.</p>'}
 $('#fixed-exam').onchange=()=>{courses();render()};$('#fixed-course').onchange=render;$('#fixed-query').oninput=render;
 $$('#fixed-sort button').forEach(b=>b.onclick=()=>{sortMode=b.dataset.sort;$$('#fixed-sort button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});
 courses();render();
}
export function renderScore(out,data){
 const d=data.scores;let saved={};try{saved=JSON.parse(localStorage.getItem('universe-preview-scores')||'{}')}catch{}
 out.innerHTML=`<div class="score-intro"><span class="p-label">TU CARRERA / TU REFERENCIA</span><p>Calcula tu puntaje CEPREUNI y compara los cortes históricos disponibles para tu carrera.</p></div><div class="score-layout"><section class="p-panel"><div class="score-selectors"><label>Carrera<select id="score-career" class="p-select">${d.careers.map(([code,name])=>`<option value="${esc(code)}">${esc(name)}</option>`).join('')}</select></label><label>Sede<select id="score-site" class="p-select"><option>Lima</option><option>Juliaca</option></select></label></div><div class="p-subhead"><h2>Tus notas actuales</h2><small>0–150 puntos · deja vacía la que aún no rindes</small></div><div class="score-grades">${labels.map((t,i)=>`<label class="grade-row"><span>${t}</span><input class="p-input" type="number" min="0" max="150" step="0.01" inputmode="decimal" data-grade="${i}" aria-label="Nota ${t}" placeholder="—"></label>`).join('')}</div><div id="score-vocational" hidden><div class="p-subhead"><h3>Arquitectura · Vocacional</h3></div><div class="score-grades">${Array.from({length:7},(_,i)=>`<label class="grade-row"><span>${i===6?'Vocacional DIAD':'Taller '+(i+1)}</span><input class="p-input" type="number" min="0" max="${i===6?200:90}" step="0.01" inputmode="decimal" data-voc="${i}" aria-label="${i===6?'Vocacional DIAD':'Taller '+(i+1)}" placeholder="máx ${i===6?200:90}"></label>`).join('')}</div></div><p id="score-error" class="score-error" role="alert"></p><p class="source-note">Se guardan solo en este navegador. No pedimos tu código ni importamos datos personales.</p><button id="score-clear" class="text-button">Borrar mis notas</button></section><aside class="score-side"><section class="p-panel" id="score-result" aria-live="polite"></section></aside></div><section class="p-panel score-history"><div class="p-subhead"><h2>Una referencia, no una promesa.</h2><span>Escala de 0 a 20</span></div><div id="score-history"></div><p class="source-note">Promedio aritmético de los puntajes mínimos disponibles por ciclo y sede; no es el promedio de todos los ingresantes. Se excluyen mínimos desconocidos. Los rangos provienen del registro agregado del proyecto original; los documentos de años anteriores requieren revalidación. No equivalen a una vacante garantizada.</p></section><details class="p-panel score-method"><summary>Cómo se calcula y cuáles son las fuentes</summary><p>PID = S + 2 × EP1 + 4 × EP2 + 6 × EF. S suma las cinco mejores prácticas entre las seis primeras y la séptima, que es obligatoria. Máximo: 2700 puntos.</p><p>Arquitectura: PAD = PID + 1.54 × (SV + PVD). SV conserva los cinco mejores talleres de seis (90 puntos cada uno); PVD admite 200. Máximo: 3701.</p><p>El avance parcial divide los puntos conocidos entre su máximo ponderado conocido. No trata lo pendiente como cero.</p><p>${external(d.guide,'Guía oficial CEPREUNI 2026-2 · fórmula verificada')} · ${external(d.results,'Resultados oficiales UNI')}</p></details>`;
 $('#score-career').value=d.careers.some(c=>c[0]===saved.career)?saved.career:'C1';$('#score-site').value=saved.site==='Juliaca'?'Juliaca':'Lima';
 document.querySelectorAll('[data-grade]').forEach((el,i)=>el.value=saved.grades?.[i]??'');document.querySelectorAll('[data-voc]').forEach((el,i)=>el.value=saved.vocational?.[i]??'');
 function render(){const career=$('#score-career').value,site=$('#score-site').value,arch=career==='A1',g=[...document.querySelectorAll('[data-grade]')].map(e=>e.value),v=[...document.querySelectorAll('[data-voc]')].map(e=>e.value);
 $('#score-vocational').hidden=!arch;$('#score-error').textContent='';
 const rows=historyRows(d.cutoffs,career,site),average=cutoffMean(rows);
 $('#score-history').innerHTML=`<div class="history-summary"><b>${average?num(average.mean,3):'Sin referencia'}</b><span>${average?'Promedio de cortes mínimos · '+average.count+' ciclos':'No hay mínimos documentados para esta combinación'}</span></div><div class="table-scroll"><table><thead><tr><th>Ciclo · ${esc(site)}</th><th>Mínimo</th><th>Máximo</th><th>Rango histórico</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.cycle)}</td><td>${num(r.range[0],3)}</td><td>${num(r.range[1],3)}</td><td><div class="score-bar">${r.range[0]!==null&&r.range[1]!==null?`<i style="left:${r.range[0]/20*100}%;width:${Math.max(.5,(r.range[1]-r.range[0])/20*100)}%"></i>`:'Sin rango completo'}</div></td></tr>`).join('')}</tbody></table></div>`;
 try{const result=computeScore(g,arch,v),needed=average?requiredPercent(g,arch,v,average.mean):null;
 $('#score-result').innerHTML=`<span class="p-label">${result.complete?'PUNTAJE FINAL CALCULADO':'AVANCE PARCIAL · NO ES NOTA FINAL'}</span><div class="score-big">${num(result.normalized)}<small>/20</small></div><p>${result.entered}/10 evaluaciones generales ingresadas</p><div class="score-breakdown"><span>${arch?'PAD':'PID'} acumulado<b>${num(result.points,1)}</b></span><span>Máximo de lo ingresado<b>${num(result.possible,1)}</b></span><span>S (prácticas incluidas)<b>${num(result.s,1)}</b></span></div>${!result.complete&&average?`<p class="score-goal">${needed===null?'Con las notas registradas ya no es posible alcanzar el promedio histórico en lo que resta.':needed===0?'El puntaje ya acumulado alcanza esa referencia histórica.':`Para igualar el promedio histórico necesitarías aproximadamente <strong>${num(needed*1.5,1)}/150</strong> en cada evaluación general pendiente${arch?', y '+num(needed,1)+'% en lo vocacional pendiente':''}.`}</p>`:result.complete&&average?`<p class="score-goal">${result.final20>=average.mean?'Tu puntaje final supera el promedio histórico de cortes.':'Tu puntaje final queda por debajo del promedio histórico de cortes.'}</p>`:''}`;
 try{localStorage.setItem('universe-preview-scores',JSON.stringify({career,site,grades:g,vocational:v}))}catch{}
 }catch(e){$('#score-error').textContent=e.message;$('#score-result').innerHTML='<p>Revisa las notas señaladas antes de calcular.</p>'}
 }
 out.querySelectorAll('input,select').forEach(e=>e.addEventListener(e.tagName==='SELECT'?'change':'input',render));$('#score-clear').onclick=()=>{out.querySelectorAll('[data-grade],[data-voc]').forEach(e=>e.value='');render()};render();
}
